module.exports = {
  apps: [
    {
      name:        'content-factory',
      script:      'dist/factory.js',
      instances:   1,
      autorestart: true,
      watch:       false,
      env:         { NODE_ENV: 'production' },
    },
    {
      name:        'video-worker-1',
      script:      'dist/index.js',
      instances:   1,
      autorestart: true,
      watch:       false,
      env:         { NODE_ENV: 'production', WORKER_ID: 'W1' },
    },
    {
      name:        'video-worker-2',
      script:      'dist/index.js',
      instances:   1,
      autorestart: true,
      watch:       false,
      env:         { NODE_ENV: 'production', WORKER_ID: 'W2' },
    },
    {
      name:        'seo-optimizer',
      script:      'dist/seo-optimizer.js',
      instances:   1,
      autorestart: true,
      watch:       false,
      env:         { NODE_ENV: 'production' },
    },
    {
      name:        'status-reporter',
      script:      'dist/status-reporter.js',
      instances:   1,
      autorestart: true,
      watch:       false,
      env:         { NODE_ENV: 'production' },
    },
    {
      name:        'routines-runner',
      script:      'dist/routines-runner.js',
      instances:   1,
      autorestart: true,
      watch:       false,
      env:         {
        NODE_ENV: 'production',
        ROUTINES_SERVICE_ID:   'local-agent-macmini',
        ROUTINES_SERVICE_NAME: 'Routines Runner (Mac mini)',
        WATCHDOG_HOST_ID:      'cli-l',
      },
    },
  ],
}
