import type {
  FinCustomer,
  FinInvoice,
  FinPayment,
  FinReminder,
  FinIncassoCase,
  FinTimeline,
  FinWorkflowRule,
  FinTemplate,
  FinDashboardStats,
} from './types'

export const MOCK_CUSTOMERS: FinCustomer[] = [
  {
    id: 'cust-1',
    company_id: 'strkbeheer',
    name: 'Renovatie Groep Dijkstra BV',
    kvk: '12345678',
    btw: 'NL123456789B01',
    email: 'info@dijkstra-renovatie.nl',
    phone: '020-1234567',
    address: 'Herengracht 100',
    city: 'Amsterdam',
    score: 82,
    risk_level: 'laag',
    payment_avg_days: 18,
  },
  {
    id: 'cust-2',
    company_id: 'strkbeheer',
    name: 'Bouwbedrijf Van den Berg',
    kvk: '23456789',
    btw: 'NL234567890B01',
    email: 'administratie@vandenberg-bouw.nl',
    phone: '010-2345678',
    address: 'Coolsingel 55',
    city: 'Rotterdam',
    score: 61,
    risk_level: 'midden',
    payment_avg_days: 34,
  },
  {
    id: 'cust-3',
    company_id: 'strkbouw',
    name: 'Technische Installaties Hoekstra',
    kvk: '34567890',
    btw: 'NL345678901B01',
    email: 'finance@hoekstra-ti.nl',
    phone: '070-3456789',
    address: 'Binckhorstlaan 200',
    city: 'Den Haag',
    score: 44,
    risk_level: 'hoog',
    payment_avg_days: 52,
  },
  {
    id: 'cust-4',
    company_id: 'strkbouw',
    name: 'Architectenbureau De Vries & Partners',
    kvk: '45678901',
    btw: 'NL456789012B01',
    email: 'boekhouding@devries-arch.nl',
    phone: '030-4567890',
    address: 'Maartensdijk 10',
    city: 'Utrecht',
    score: 90,
    risk_level: 'laag',
    payment_avg_days: 12,
  },
  {
    id: 'cust-5',
    company_id: 'strkbeheer',
    name: 'Vastgoed Exploitatie Janssen NV',
    kvk: '56789012',
    btw: 'NL567890123B01',
    email: 'debiteuren@janssen-vastgoed.nl',
    phone: '020-5678901',
    address: 'Zuidas 300',
    city: 'Amsterdam',
    score: 35,
    risk_level: 'hoog',
    payment_avg_days: 68,
  },
]

export const MOCK_INVOICES: FinInvoice[] = [
  {
    id: 'inv-1',
    company_id: 'strkbeheer',
    customer_id: 'cust-1',
    invoice_nr: 'INV-2025-001',
    description: 'Renovatiewerkzaamheden fase 1 — Herengracht 100',
    amount_excl: 18500,
    vat_pct: 21,
    amount_vat: 3885,
    amount_incl: 22385,
    amount_paid: 0,
    issued_at: '2025-04-01',
    due_date: '2025-05-01',
    paid_at: undefined,
    status: 'open',
    days_overdue: 0,
    workflow_stage: 'herinnering_1',
    customer: MOCK_CUSTOMERS[0],
  },
  {
    id: 'inv-2',
    company_id: 'strkbeheer',
    customer_id: 'cust-2',
    invoice_nr: 'INV-2025-002',
    description: 'Bouwbegeleiding nieuwbouw — Coolsingel 55',
    amount_excl: 8750,
    vat_pct: 21,
    amount_vat: 1837.5,
    amount_incl: 10587.5,
    amount_paid: 0,
    issued_at: '2025-03-15',
    due_date: '2025-04-14',
    paid_at: undefined,
    status: 'vervallen',
    days_overdue: 7,
    workflow_stage: 'aanmaning_1',
    customer: MOCK_CUSTOMERS[1],
  },
  {
    id: 'inv-3',
    company_id: 'strkbouw',
    customer_id: 'cust-3',
    invoice_nr: 'INV-2025-003',
    description: 'Installatie CV-systeem — Binckhorstlaan 200',
    amount_excl: 37200,
    vat_pct: 21,
    amount_vat: 7812,
    amount_incl: 45012,
    amount_paid: 0,
    issued_at: '2025-03-01',
    due_date: '2025-03-31',
    paid_at: undefined,
    status: 'incasso',
    days_overdue: 21,
    workflow_stage: 'incasso',
    customer: MOCK_CUSTOMERS[2],
  },
  {
    id: 'inv-4',
    company_id: 'strkbouw',
    customer_id: 'cust-4',
    invoice_nr: 'INV-2025-004',
    description: 'Architectuuradvies stedenbouwkundig plan Utrecht',
    amount_excl: 5500,
    vat_pct: 21,
    amount_vat: 1155,
    amount_incl: 6655,
    amount_paid: 6655,
    issued_at: '2025-04-10',
    due_date: '2025-05-10',
    paid_at: '2025-04-22',
    status: 'betaald',
    days_overdue: 0,
    workflow_stage: 'afgerond',
    customer: MOCK_CUSTOMERS[3],
  },
  {
    id: 'inv-5',
    company_id: 'strkbeheer',
    customer_id: 'cust-5',
    invoice_nr: 'INV-2025-005',
    description: 'Beheerkosten Q1 2025 — Vastgoed portfolio Janssen',
    amount_excl: 12000,
    vat_pct: 21,
    amount_vat: 2520,
    amount_incl: 14520,
    amount_paid: 14520,
    issued_at: '2025-01-31',
    due_date: '2025-03-02',
    paid_at: '2025-03-15',
    status: 'betaald',
    days_overdue: 0,
    workflow_stage: 'afgerond',
    customer: MOCK_CUSTOMERS[4],
  },
  {
    id: 'inv-6',
    company_id: 'strkbeheer',
    customer_id: 'cust-2',
    invoice_nr: 'INV-2025-006',
    description: 'Constructieadvies uitbreiding bedrijfspand Rotterdam',
    amount_excl: 4200,
    vat_pct: 21,
    amount_vat: 882,
    amount_incl: 5082,
    amount_paid: 0,
    issued_at: '2025-04-15',
    due_date: '2025-05-15',
    paid_at: undefined,
    status: 'open',
    days_overdue: 0,
    workflow_stage: 'nieuw',
    customer: MOCK_CUSTOMERS[1],
  },
  {
    id: 'inv-7',
    company_id: 'strkbouw',
    customer_id: 'cust-5',
    invoice_nr: 'INV-2025-007',
    description: 'Dakwerkzaamheden appartementencomplex Zuidas',
    amount_excl: 28000,
    vat_pct: 21,
    amount_vat: 5880,
    amount_incl: 33880,
    amount_paid: 0,
    issued_at: '2025-03-20',
    due_date: '2025-04-19',
    paid_at: undefined,
    status: 'vervallen',
    days_overdue: 12,
    workflow_stage: 'aanmaning_2',
    customer: MOCK_CUSTOMERS[4],
  },
  {
    id: 'inv-8',
    company_id: 'strkbeheer',
    customer_id: 'cust-1',
    invoice_nr: 'INV-2025-008',
    description: 'Projectmanagement renovatie fase 2',
    amount_excl: 9800,
    vat_pct: 21,
    amount_vat: 2058,
    amount_incl: 11858,
    amount_paid: 0,
    issued_at: '2025-04-20',
    due_date: '2025-05-20',
    paid_at: undefined,
    status: 'open',
    days_overdue: 0,
    workflow_stage: 'nieuw',
    customer: MOCK_CUSTOMERS[0],
  },
]

export const MOCK_PAYMENTS: FinPayment[] = [
  {
    id: 'pay-1',
    invoice_id: 'inv-4',
    amount: 6655,
    method: 'bank',
    reference: 'INV-2025-004',
    paid_at: '2025-04-22',
  },
  {
    id: 'pay-2',
    invoice_id: 'inv-5',
    amount: 14520,
    method: 'bank',
    reference: 'INV-2025-005',
    paid_at: '2025-03-15',
  },
]

export const MOCK_REMINDERS: FinReminder[] = [
  {
    id: 'rem-1',
    invoice_id: 'inv-1',
    type: 'email',
    subject: 'Vriendelijke betalingsherinnering — INV-2025-001',
    sent_at: '2025-05-03',
    opened_at: '2025-05-03',
    stage: 'herinnering_1',
  },
  {
    id: 'rem-2',
    invoice_id: 'inv-2',
    type: 'email',
    subject: 'Eerste aanmaning — INV-2025-002',
    sent_at: '2025-04-20',
    opened_at: undefined,
    stage: 'aanmaning_1',
  },
  {
    id: 'rem-3',
    invoice_id: 'inv-7',
    type: 'email',
    subject: 'Tweede aanmaning — dringende betaalverzoek',
    sent_at: '2025-05-01',
    opened_at: '2025-05-02',
    stage: 'aanmaning_2',
  },
]

export const MOCK_INCASSO_CASES: FinIncassoCase[] = [
  {
    id: 'inc-1',
    invoice_id: 'inv-3',
    company_id: 'strkbouw',
    status: 'actief',
    amount_principal: 45012,
    amount_interest: 450.12,
    amount_costs: 750,
    amount_total: 46212.12,
    incasso_party: 'Inkassio Nederland BV',
    started_at: '2025-04-21',
  },
]

export const MOCK_TIMELINE: FinTimeline[] = [
  {
    id: 'tl-1',
    invoice_id: 'inv-1',
    event_type: 'invoice_created',
    title: 'Factuur aangemaakt',
    description: 'Factuur INV-2025-001 aangemaakt voor €22.385',
    amount: 22385,
    performed_by: 'Orlando',
    created_at: '2025-04-01T09:00:00Z',
  },
  {
    id: 'tl-2',
    invoice_id: 'inv-1',
    event_type: 'email_sent',
    title: 'Factuur verzonden',
    description: 'Factuur per e-mail verzonden naar info@dijkstra-renovatie.nl',
    performed_by: 'Systeem',
    created_at: '2025-04-01T09:05:00Z',
  },
  {
    id: 'tl-3',
    invoice_id: 'inv-1',
    event_type: 'overdue',
    title: 'Factuur vervallen',
    description: 'Betaaltermijn van 30 dagen verstreken',
    performed_by: 'Systeem',
    created_at: '2025-05-01T00:00:00Z',
  },
  {
    id: 'tl-4',
    invoice_id: 'inv-1',
    event_type: 'email_sent',
    title: 'Herinnering verstuurd',
    description: 'Vriendelijke betalingsherinnering per e-mail verstuurd',
    performed_by: 'Workflow Engine',
    created_at: '2025-05-03T08:00:00Z',
  },
  {
    id: 'tl-5',
    invoice_id: 'inv-1',
    event_type: 'email_opened',
    title: 'Herinnering geopend',
    description: 'Ontvanger heeft de e-mail geopend',
    performed_by: 'Tracking',
    created_at: '2025-05-03T10:23:00Z',
  },
]

export const MOCK_WORKFLOW_RULES: FinWorkflowRule[] = [
  {
    id: 'wf-1',
    company_id: 'strkbeheer',
    name: 'Pre-vervaldatum herinnering',
    trigger_type: 'days_before_due',
    trigger_days: 3,
    action_type: 'send_email',
    active: true,
  },
  {
    id: 'wf-2',
    company_id: 'strkbeheer',
    name: 'Dag 1 na vervaldatum',
    trigger_type: 'days_overdue',
    trigger_days: 1,
    action_type: 'send_reminder',
    active: true,
  },
  {
    id: 'wf-3',
    company_id: 'strkbeheer',
    name: 'Eerste aanmaning dag 7',
    trigger_type: 'days_overdue',
    trigger_days: 7,
    action_type: 'send_aanmaning',
    active: true,
  },
  {
    id: 'wf-4',
    company_id: 'strkbeheer',
    name: 'Tweede aanmaning dag 14',
    trigger_type: 'days_overdue',
    trigger_days: 14,
    action_type: 'send_aanmaning_2',
    active: true,
  },
  {
    id: 'wf-5',
    company_id: 'strkbeheer',
    name: 'Sommatie dag 21',
    trigger_type: 'days_overdue',
    trigger_days: 21,
    action_type: 'send_sommatie',
    active: true,
  },
  {
    id: 'wf-6',
    company_id: 'strkbeheer',
    name: 'Incasso escalatie dag 30',
    trigger_type: 'days_overdue',
    trigger_days: 30,
    action_type: 'escalate_incasso',
    active: true,
  },
  {
    id: 'wf-7',
    company_id: 'strkbouw',
    name: 'Pre-vervaldatum herinnering',
    trigger_type: 'days_before_due',
    trigger_days: 3,
    action_type: 'send_email',
    active: true,
  },
  {
    id: 'wf-8',
    company_id: 'strkbouw',
    name: 'Aanmaning dag 7',
    trigger_type: 'days_overdue',
    trigger_days: 7,
    action_type: 'send_aanmaning',
    active: true,
  },
  {
    id: 'wf-9',
    company_id: 'strkbouw',
    name: 'Incasso escalatie dag 21',
    trigger_type: 'days_overdue',
    trigger_days: 21,
    action_type: 'escalate_incasso',
    active: false,
  },
]

export const MOCK_TEMPLATES: FinTemplate[] = [
  {
    id: 'tmpl-1',
    company_id: 'strkbeheer',
    name: 'Vriendelijke herinnering',
    type: 'email',
    stage: 'herinnering_1',
    subject: 'Vriendelijke betalingsherinnering — {{invoice_nr}}',
    body: 'Beste {{klant_naam}},\n\nHierbij herinneren wij u vriendelijk aan onze openstaande factuur {{invoice_nr}} van {{amount_incl}} met vervaldatum {{due_date}}.\n\nMocht u reeds betaald hebben, dan kunt u deze herinnering als niet verzonden beschouwen.\n\nMet vriendelijke groet,\n{{bedrijf_naam}}',
    tone: 'vriendelijk',
    active: true,
  },
  {
    id: 'tmpl-2',
    company_id: 'strkbeheer',
    name: 'Eerste aanmaning',
    type: 'email',
    stage: 'aanmaning_1',
    subject: 'Aanmaning — Openstaande factuur {{invoice_nr}}',
    body: 'Beste {{klant_naam}},\n\nOndanks onze eerdere herinnering constateren wij dat factuur {{invoice_nr}} van {{amount_incl}}, met vervaldatum {{due_date}}, nog niet is voldaan.\n\nWij verzoeken u dringend het openstaande bedrag binnen 7 dagen over te maken.\n\nMet zakelijke groet,\n{{bedrijf_naam}}',
    tone: 'zakelijk',
    active: true,
  },
  {
    id: 'tmpl-3',
    company_id: 'strkbeheer',
    name: 'Laatste sommatie voor incasso',
    type: 'email',
    stage: 'sommatie',
    subject: 'SOMMATIE — Laatste mogelijkheid betaling {{invoice_nr}}',
    body: 'Geachte heer/mevrouw,\n\nDespite our previous reminders, invoice {{invoice_nr}} for €{{amount_incl}} remains outstanding for {{days_overdue}} days.\n\nThis is your final notice before we transfer this matter to our collection agency. Payment must be received within 5 working days.\n\nAdditional costs and statutory interest will be charged.\n\nMet formele groet,\n{{bedrijf_naam}}',
    tone: 'formeel',
    active: true,
  },
  {
    id: 'tmpl-4',
    company_id: 'strkbeheer',
    name: 'WhatsApp follow-up',
    type: 'whatsapp',
    stage: 'herinnering_1',
    subject: undefined,
    body: 'Hallo {{klant_naam}}, we hebben u een betalingsherinnering gestuurd voor factuur {{invoice_nr}} (€{{amount_incl}}). Heeft u dit ontvangen? Bel ons gerust op {{bedrijf_telefoon}} als u vragen heeft.',
    tone: 'vriendelijk',
    active: true,
  },
]

export function getMockDashboardStats(): FinDashboardStats {
  const openInvoices = MOCK_INVOICES.filter((i) => i.status === 'open')
  const overdueInvoices = MOCK_INVOICES.filter((i) => i.status === 'vervallen')
  const incassoInvoices = MOCK_INVOICES.filter((i) => i.status === 'incasso')
  const paidInvoices = MOCK_INVOICES.filter((i) => i.status === 'betaald')

  const totalOpen = openInvoices.reduce((s, i) => s + i.amount_incl, 0)
  const totalOverdue = overdueInvoices.reduce((s, i) => s + i.amount_incl, 0)
  const totalIncasso = incassoInvoices.reduce((s, i) => s + i.amount_incl, 0)
  const totalPaid = paidInvoices.reduce((s, i) => s + i.amount_incl, 0)
  const allNonPaid = openInvoices.length + overdueInvoices.length + incassoInvoices.length

  return {
    total_open: openInvoices.length,
    total_open_amount: totalOpen,
    total_overdue: overdueInvoices.length,
    total_overdue_amount: totalOverdue,
    total_incasso: incassoInvoices.length,
    total_incasso_amount: totalIncasso,
    total_paid_month: paidInvoices.length,
    total_paid_month_amount: totalPaid,
    avg_payment_days: 24,
    overdue_pct: allNonPaid > 0 ? Math.round((overdueInvoices.length / allNonPaid) * 100) : 0,
  }
}
