-- Migration 085 — Checkout Audit Artifacts Storage bucket
-- Creates private Supabase Storage bucket for screenshots, HAR logs, videos, reports
-- Generated by checkout-auditor service; service_role only access.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'checkout-audit-artifacts',
  'checkout-audit-artifacts',
  false,
  52428800,  -- 50 MB
  array[
    'image/png',
    'image/jpeg',
    'image/webp',
    'video/webm',
    'video/mp4',
    'application/json',
    'text/html',
    'text/markdown',
    'text/plain',
    'application/zip'
  ]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- RLS: block anon/authenticated from this bucket entirely. service_role bypasses RLS.
drop policy if exists "checkout_audit_artifacts_select_none" on storage.objects;
create policy "checkout_audit_artifacts_select_none"
  on storage.objects
  for select
  to anon, authenticated
  using (bucket_id != 'checkout-audit-artifacts');

drop policy if exists "checkout_audit_artifacts_insert_none" on storage.objects;
create policy "checkout_audit_artifacts_insert_none"
  on storage.objects
  for insert
  to anon, authenticated
  with check (bucket_id != 'checkout-audit-artifacts');

drop policy if exists "checkout_audit_artifacts_update_none" on storage.objects;
create policy "checkout_audit_artifacts_update_none"
  on storage.objects
  for update
  to anon, authenticated
  using (bucket_id != 'checkout-audit-artifacts');

drop policy if exists "checkout_audit_artifacts_delete_none" on storage.objects;
create policy "checkout_audit_artifacts_delete_none"
  on storage.objects
  for delete
  to anon, authenticated
  using (bucket_id != 'checkout-audit-artifacts');
