-- Seed registry: every check organization watchdog must run.
-- Reuses slugs as natural keys so re-running the migration is idempotent.
-- Adjust thresholds by updating this seed and re-applying, or via SQL UI.
--
-- Categories:
--   render-engine  → web/worker on Render (http_ping where available)
--   vercel-cron    → Vercel scheduled function (heartbeat from the route)
--   render-cron    → node-cron inside an engine (heartbeat from the job)
--   queue          → orchestrator/acq_scan_jobs depth + age
--   data           → table freshness (e.g. youtube stats, scraper sources)

insert into public.infra_watchdog_checks
  (slug, display_name, check_type, layer, category, config, threshold, interval_seconds, consecutive_failures_to_escalate, severity, notes)
values
  -- ───── HTTP ping: every Render web service with /health ─────
  ('engine.mail-engine.health', 'Mail Engine /health', 'http_ping', 'app', 'render-engine',
    '{"url":"https://orlando-mail-engine.onrender.com/health","timeout_ms":8000}',
    '{"max_latency_ms":5000}',
    120, 3, 'error', 'Web service. Free tier may cold-start.'),
  ('engine.executive-engine.health', 'Executive Engine /health', 'http_ping', 'app', 'render-engine',
    '{"url":"https://orlando-executive-engine.onrender.com/health","timeout_ms":8000}',
    '{"max_latency_ms":5000}',
    120, 3, 'error', null),
  ('engine.acquisition-engine.health', 'Acquisition Engine /health', 'http_ping', 'app', 'render-engine',
    '{"url":"https://orlando-acquisition-engine.onrender.com/health","timeout_ms":8000}',
    '{"max_latency_ms":5000}',
    120, 3, 'error', null),
  ('engine.language-engine.health', 'Language Engine /health', 'http_ping', 'app', 'render-engine',
    '{"url":"https://orlando-language-engine.onrender.com/health","timeout_ms":8000}',
    '{"max_latency_ms":5000}',
    300, 3, 'warning', 'autoDeploy=false, optional service.'),
  ('engine.watchdog.health', 'Watchdog self /health', 'http_ping', 'infra', 'render-engine',
    '{"url":"https://orlando-watchdog.onrender.com/health","timeout_ms":8000}',
    '{"max_latency_ms":5000}',
    300, 3, 'critical', 'Self-ping. If watchdog itself goes down, Render watchdog at infra layer should still alert via deploy.'),

  -- ───── Heartbeats: workers without HTTP (youtube-engine, executor, competitor-scanner) ─────
  ('engine.youtube-engine.tick', 'YouTube Engine main loop', 'heartbeat', 'app', 'render-worker',
    '{"slug":"engine.youtube-engine.tick"}',
    '{"max_age_seconds":900}',
    180, 2, 'error', 'Engine should heartbeat every ~5 min from its main tick. Threshold 15 min.'),
  ('engine.executor.tick', 'Planning/Executor main loop', 'heartbeat', 'app', 'render-worker',
    '{"slug":"engine.executor.tick"}',
    '{"max_age_seconds":900}',
    180, 2, 'error', null),
  ('engine.competitor-scanner.tick', 'Competitor Scanner main loop', 'heartbeat', 'app', 'render-worker',
    '{"slug":"engine.competitor-scanner.tick"}',
    '{"max_age_seconds":1800}',
    300, 2, 'warning', 'Runs less frequently. Threshold 30 min.'),

  -- ───── Vercel crons: heartbeat from each route (route writes after success) ─────
  ('cron.vercel.refresh-tokens', 'Vercel cron: refresh-tokens (5:00 daily)', 'cron_lateness', 'app', 'vercel-cron',
    '{"slug":"cron.vercel.refresh-tokens","schedule":"0 5 * * *"}',
    '{"grace_seconds":3600}',
    600, 1, 'error', 'Daily 05:00. Missing run blocks all YouTube uploads.'),
  ('cron.vercel.sync-stats', 'Vercel cron: sync-stats (30m)', 'cron_lateness', 'app', 'vercel-cron',
    '{"slug":"cron.vercel.sync-stats","schedule":"*/30 * * * *"}',
    '{"grace_seconds":1800}',
    600, 2, 'warning', null),
  ('cron.vercel.refresh-video-stats', 'Vercel cron: refresh-video-stats (30m)', 'cron_lateness', 'app', 'vercel-cron',
    '{"slug":"cron.vercel.refresh-video-stats","schedule":"*/30 * * * *"}',
    '{"grace_seconds":1800}',
    600, 2, 'warning', null),
  ('cron.vercel.sync-to-media-metrics', 'Vercel cron: sync-to-media-metrics (30m)', 'cron_lateness', 'app', 'vercel-cron',
    '{"slug":"cron.vercel.sync-to-media-metrics","schedule":"*/30 * * * *"}',
    '{"grace_seconds":1800}',
    600, 2, 'warning', null),
  ('cron.vercel.snapshot-daily-stats', 'Vercel cron: snapshot-daily-stats (23:55)', 'cron_lateness', 'app', 'vercel-cron',
    '{"slug":"cron.vercel.snapshot-daily-stats","schedule":"55 23 * * *"}',
    '{"grace_seconds":3600}',
    600, 1, 'error', null),
  ('cron.vercel.run-pipeline', 'Vercel cron: run-pipeline (02:00)', 'cron_lateness', 'app', 'vercel-cron',
    '{"slug":"cron.vercel.run-pipeline","schedule":"0 2 * * *"}',
    '{"grace_seconds":3600}',
    900, 1, 'error', null),
  ('cron.vercel.sync-video-analytics', 'Vercel cron: sync-video-analytics (10:00)', 'cron_lateness', 'app', 'vercel-cron',
    '{"slug":"cron.vercel.sync-video-analytics","schedule":"0 10 * * *"}',
    '{"grace_seconds":3600}',
    900, 1, 'warning', null),
  ('cron.vercel.viral-scan', 'Vercel cron: viral-scan (4h)', 'cron_lateness', 'app', 'vercel-cron',
    '{"slug":"cron.vercel.viral-scan","schedule":"0 */4 * * *"}',
    '{"grace_seconds":3600}',
    900, 2, 'warning', null),
  ('cron.vercel.audio-scan', 'Vercel cron: audio-scan (4h)', 'cron_lateness', 'app', 'vercel-cron',
    '{"slug":"cron.vercel.audio-scan","schedule":"15 */4 * * *"}',
    '{"grace_seconds":3600}',
    900, 2, 'warning', null),
  ('cron.vercel.trend-scan', 'Vercel cron: trend-scan (4h)', 'cron_lateness', 'app', 'vercel-cron',
    '{"slug":"cron.vercel.trend-scan","schedule":"30 */4 * * *"}',
    '{"grace_seconds":3600}',
    900, 2, 'warning', null),
  ('cron.vercel.content-factory', 'Vercel cron: content-factory (10m)', 'cron_lateness', 'app', 'vercel-cron',
    '{"slug":"cron.vercel.content-factory","schedule":"*/10 * * * *"}',
    '{"grace_seconds":1200}',
    300, 2, 'error', 'Core content pipeline. 10-min cadence.'),
  ('cron.vercel.renderer-dispatch', 'Vercel cron: renderer-dispatch (5m)', 'cron_lateness', 'app', 'vercel-cron',
    '{"slug":"cron.vercel.renderer-dispatch","schedule":"*/5 * * * *"}',
    '{"grace_seconds":600}',
    300, 2, 'error', null),
  ('cron.vercel.renderer-poll', 'Vercel cron: renderer-poll (2m)', 'cron_lateness', 'app', 'vercel-cron',
    '{"slug":"cron.vercel.renderer-poll","schedule":"*/2 * * * *"}',
    '{"grace_seconds":300}',
    180, 2, 'error', null),
  ('cron.vercel.atlas-upload', 'Vercel cron: atlas-upload (5m)', 'cron_lateness', 'app', 'vercel-cron',
    '{"slug":"cron.vercel.atlas-upload","schedule":"*/5 * * * *"}',
    '{"grace_seconds":600}',
    300, 2, 'error', null),
  ('cron.vercel.executive.decision', 'Vercel cron: executive decision (1h)', 'cron_lateness', 'app', 'vercel-cron',
    '{"slug":"cron.vercel.executive.decision","schedule":"0 * * * *"}',
    '{"grace_seconds":900}',
    900, 2, 'warning', null),
  ('cron.vercel.executive.alert', 'Vercel cron: executive alert (15m)', 'cron_lateness', 'app', 'vercel-cron',
    '{"slug":"cron.vercel.executive.alert","schedule":"*/15 * * * *"}',
    '{"grace_seconds":900}',
    600, 2, 'warning', null),
  ('cron.vercel.executive.scaling', 'Vercel cron: executive autonomous-scaling (2h)', 'cron_lateness', 'app', 'vercel-cron',
    '{"slug":"cron.vercel.executive.scaling","schedule":"0 */2 * * *"}',
    '{"grace_seconds":1800}',
    1800, 2, 'warning', null),
  ('cron.vercel.factory-feeder', 'Vercel cron: factory-feeder (4h)', 'cron_lateness', 'app', 'vercel-cron',
    '{"slug":"cron.vercel.factory-feeder","schedule":"20 */4 * * *"}',
    '{"grace_seconds":1800}',
    1800, 2, 'warning', null),
  ('cron.vercel.acquisition.deal-scan', 'Vercel cron: acquisition deal-scan (6h)', 'cron_lateness', 'app', 'vercel-cron',
    '{"slug":"cron.vercel.acquisition.deal-scan","schedule":"0 */6 * * *"}',
    '{"grace_seconds":1800}',
    1800, 1, 'error', 'Verzamelaar/acquisition feed.'),
  ('cron.vercel.acquisition.permit-scan', 'Vercel cron: acquisition permit-scan (07:00)', 'cron_lateness', 'app', 'vercel-cron',
    '{"slug":"cron.vercel.acquisition.permit-scan","schedule":"0 7 * * *"}',
    '{"grace_seconds":3600}',
    1800, 1, 'error', null),
  ('cron.vercel.acquisition.offmarket-scan', 'Vercel cron: acquisition offmarket-scan (08:00)', 'cron_lateness', 'app', 'vercel-cron',
    '{"slug":"cron.vercel.acquisition.offmarket-scan","schedule":"0 8 * * *"}',
    '{"grace_seconds":3600}',
    1800, 1, 'error', null),
  ('cron.vercel.acquisition.director-briefing', 'Vercel cron: acquisition director-briefing (07:30)', 'cron_lateness', 'app', 'vercel-cron',
    '{"slug":"cron.vercel.acquisition.director-briefing","schedule":"30 7 * * *"}',
    '{"grace_seconds":3600}',
    1800, 1, 'warning', null),
  ('cron.vercel.acquisition.bouw-scan', 'Vercel cron: acquisition bouw-scan (06:00)', 'cron_lateness', 'app', 'vercel-cron',
    '{"slug":"cron.vercel.acquisition.bouw-scan","schedule":"0 6 * * *"}',
    '{"grace_seconds":3600}',
    1800, 1, 'error', null),
  ('cron.vercel.acquisition.distress-scan', 'Vercel cron: acquisition distress-scan (06:30)', 'cron_lateness', 'app', 'vercel-cron',
    '{"slug":"cron.vercel.acquisition.distress-scan","schedule":"30 6 * * *"}',
    '{"grace_seconds":3600}',
    1800, 1, 'error', null),

  -- ───── Queue depth: stuck pending work ─────
  ('queue.orchestrator_tasks.pending', 'Orchestrator queue depth', 'queue_depth', 'app', 'queue',
    '{"table":"orchestrator_tasks","status_column":"status","pending_states":["pending","queued","scheduled"],"age_column":"created_at"}',
    '{"max_pending":50,"max_age_minutes":60}',
    300, 2, 'error', 'If queue grows past 50 or oldest pending > 1h, executors are likely stuck.'),
  ('queue.acq_scan_jobs.pending', 'Acquisition scan-jobs queue', 'queue_depth', 'app', 'queue',
    '{"table":"acq_scan_jobs","status_column":"status","pending_states":["queued","running"],"age_column":"created_at"}',
    '{"max_pending":20,"max_age_minutes":120}',
    600, 2, 'warning', null),

  -- ───── Data freshness: tables that must keep getting new rows ─────
  ('data.youtube_video_stats.fresh', 'youtube_video_stats freshness', 'data_freshness', 'data', 'youtube',
    '{"table":"youtube_video_stats","timestamp_column":"created_at"}',
    '{"max_age_minutes":120}',
    900, 2, 'warning', 'Driven by sync-stats cron every 30 min.'),
  ('data.acq_deals.fresh', 'acq_deals freshness (last new deal)', 'data_freshness', 'data', 'acquisition',
    '{"table":"acq_deals","timestamp_column":"created_at"}',
    '{"max_age_minutes":1440}',
    3600, 2, 'warning', 'At least one new deal per 24h expected from verzamelaar.'),
  ('data.acq_offmarket_leads.fresh', 'acq_offmarket_leads freshness', 'data_freshness', 'data', 'acquisition',
    '{"table":"acq_offmarket_leads","timestamp_column":"created_at"}',
    '{"max_age_minutes":1440}',
    3600, 2, 'warning', null),
  ('data.acq_permits.fresh', 'acq_permits freshness', 'data_freshness', 'data', 'acquisition',
    '{"table":"acq_permits","timestamp_column":"created_at"}',
    '{"max_age_minutes":2880}',
    3600, 2, 'warning', 'Permits update less frequently — 48h grace.')
on conflict (slug) do update set
  display_name = excluded.display_name,
  check_type = excluded.check_type,
  layer = excluded.layer,
  category = excluded.category,
  config = excluded.config,
  threshold = excluded.threshold,
  interval_seconds = excluded.interval_seconds,
  consecutive_failures_to_escalate = excluded.consecutive_failures_to_escalate,
  severity = excluded.severity,
  notes = excluded.notes,
  updated_at = now();
